project:
  title: "Visão Robótica - ECT/UFRN"
  type: website
  output-dir: .

lang: pt-BR
author: "Prof. Bruno Silva"
institute: "ECT/UFRN"

format:
  revealjs:
    theme: default
    css: assets/css/logo.css
    footer: "Visão Robótica - PPGEMECA/UFRN"
    slide-level: 2
    html-math-method: katex
